### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by SyntaxRules** [showdownjs/ng-showdown#1]
I noticed the 1.0.0-beta branch removes the angular support for showdown in the core module. I'm in agreeance with splitting out this into its own repo.

I can build this functionality out. Here's my plan:

1. Rename this repo (or create a new one) called ngShowdown
2. Pull in the functionality that was in pre 1.0.0
3. Add readme details
4. Add an example
5. Publish to bower as 'ngShowdown'

@tivie What do you think of the name? (do you care?) Does this sound like a good plan?

**Comment by tivie** [comment]
Hey @SyntaxRules. I agree with your assessment, so feel free to go ahead. =) I think the name makes sense and I've already renamed the repo per your suggestion.

I would only add the following topics in your plan, before publishing to bower:
 - Update bower.json with your contribution
 - Make the testcase

@pdeschen what do you think?

**Comment by pdeschen** [comment]
All in. Unit test would be a must. 

As for the name ng-showdown of ngShowdown?

**Comment by SyntaxRules** [comment]
Just a quick update. I've been using ng-showdown in an application. It works well. I've gotten the test framework running, just have to write the tests. I still need some documentation, but that will be easy after I get the tests done.

**Comment by tivie** [comment]
@SyntaxRules Great news.

**Comment by SyntaxRules** [comment]
Done, also published to npm

**Comment by tivie** [comment]
Tests are failing on travis and also on my localhost.

**Comment by tivie** [comment]
https://travis-ci.org/showdownjs/ng-showdown
