### ISSUE TITLE
Tests are failing in Travis CI

### ISSUE THREAD

**Issue by tivie** [showdownjs/ng-showdown#12]
https://travis-ci.org/showdownjs/ng-showdown

**Comment by tivie** [comment]
Also, add me to npm repo =P

```
npm owner add tivie ng-showdown
```

**Comment by SyntaxRules** [comment]
@tivie Added.

The travis CI is working for node v0.10 and node v0.12. But it isn't working with node 0.8. I'm not super thrilled about debugging node version 0.8. Is it important that we check node v0.8?

**Comment by tivie** [comment]
humm... I'm really not sure why it fails on 0.8. The error is:

```
  ReferenceError: Can't find variable: angular
  at /home/travis/build/showdownjs/ng-showdown/src/ng-showdown.js:9
```

Regardless, since this is a client-side exclusive library, I don't really think it is necessary to test against all versions of node. In fact, node is only used for running tests so...

**Comment by SyntaxRules** [comment]
[Bower doesn't officially support node 0.8](https://github.com/bower/bower/issues/1315). So running bower via the travis ci wont work.

I removed it, an added node 0.12
