### ISSUE TITLE
Publish release 1.1.0 to NPM

### ISSUE THREAD

**Issue by ptlis** [showdownjs/ng-showdown#25]
Although the package.json has been updated, this release [hasn't been published via NPM](https://www.npmjs.com/search?q=ng-showdown).

**Comment by tivie** [comment]
@SyntaxRules

**Comment by bpkennedy** [comment]
Heyo, you mind publishing to NPM?

**Comment by MatissJanis** [comment]
+1

**Comment by tivie** [comment]
I will take care of this as soon as possible

**Comment by SyntaxRules** [comment]
Done! Let me know if you run into any more problems!
