### ISSUE TITLE
unable to add ng-showdown in Electron app

### ISSUE THREAD

**Issue by bansalvks** [showdownjs/ng-showdown#29]
![image](https://cloud.githubusercontent.com/assets/8565993/16230393/e64f1f70-37de-11e6-8457-98cc23f0e465.png)

I am trying to build a cross-platform app using electron js. In the app I am not able to integrate `ng-showdown`

**Comment by tivie** [comment]
ng-showdown requires angular to be previously loaded.

**Comment by bansalvks** [comment]
@tivie it is working fine on browser but in an **[elctron](electron.atom.io)** it is not working

**Comment by tivie** [comment]
I believe this has something to do with electron itself. I can't help you much there, since I'm not familiar with that framework. Maybe ask in their forums?

If there's something we need to change in our library to make it compatible, we will hapilly try to implement it.

**Comment by bansalvks** [comment]
Many thanks for such a humble reply. I will let you know if I get
information regarding to the error.

**Comment by SyntaxRules** [comment]
Closing, let us know what you find out!

**Comment by HadrienPierart** [comment]
I have encountered the same issue with this library and with angular-moment actually.
The issue comes from the way angular and the dependencies are required. Somehow, something is wrong with the ifs deciding wether require is supported and the module tries to start with the wrong require way.
Angular Moment has fixed this issue this way : 

```
 
 +	var isElectron = window && window.process && window.process.type;
  	if (typeof define === 'function' && define.amd) {
  		define(['angular', 'moment'], angularMoment);
 -	} else if (typeof module !== 'undefined' && module && module.exports && (typeof require === 'function')) {
 +	} else if (typeof module !== 'undefined' && module && module.exports && (typeof require === 'function') && !isElectron) {
  		module.exports = angularMoment(require('angular'), require('moment'));
  	} else {
  		angularMoment(angular, (typeof global !== 'undefined' ? global : window).moment);
```
