### ISSUE TITLE
Populate dist/ files or point package.json main at src/

### ISSUE THREAD

**Issue by rjmackay** [showdownjs/ng-showdown#5]
Currently `require('ng-showdown')` doesn't work because it'll load `./dist/ng-showdown.js` which is empty.
Can this either be pointed at the src file or the dist file get populated with a real build?

**Comment by tivie** [comment]
We haven't update the library yet. I will fix this as soon as possible

**Comment by acourtiol** [comment]
Any news of when this will be ready ? :smiley:

**Comment by acourtiol** [comment]
Any chance to get this merged soon ? :+1:

**Comment by SyntaxRules** [comment]
#8 solved this the 'real build' way.So closing in favor of that pull request. I'll release it as an official release when I can get some unit testing in the project.
